runtime: nodejs22
service: sheldon-final-todo-app
env: standard

instance_class: F1

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 0
  max_instances: 10

handlers:
  - url: /.*
    script: auto

env_variables:
  NODE_ENV: "production"
